"""R46 P1: 统一错误码 - 三段式 DOMAIN.OPERATION.REASON

格式: DOMAIN.OPERATION.REASON
示例:
  UPLOAD.COPY.TELEGRAM_TIMEOUT
  INDEX.FINALIZE.OUTBOX_FAILED
  DELIVERY.SEND.FLOOD_WAIT
  AUTH.MFA.REPLAYED
  BACKUP.RESTORE.APPROVAL_INVALID
"""
from __future__ import annotations

# 错误码常量(按 DOMAIN 分组)
class ErrorCodes:
    # UPLOAD
    UPLOAD_COPY_TELEGRAM_TIMEOUT = "UPLOAD.COPY.TELEGRAM_TIMEOUT"
    UPLOAD_COPY_TELEGRAM_FORBIDDEN = "UPLOAD.COPY.TELEGRAM_FORBIDDEN"
    UPLOAD_MANIFEST_OUTBOX_FAILED = "UPLOAD.MANIFEST.OUTBOX_FAILED"
    UPLOAD_PENDING_OUTBOX_TX_FAILED = "UPLOAD.PENDING.OUTBOX_TX_FAILED"

    # INDEX
    INDEX_FINALIZE_OUTBOX_FAILED = "INDEX.FINALIZE.OUTBOX_FAILED"
    INDEX_CODE_CONFLICT = "INDEX.CODE.CONFLICT"

    # DELIVERY
    DELIVERY_SEND_FLOOD_WAIT = "DELIVERY.SEND.FLOOD_WAIT"
    DELIVERY_SEND_FORBIDDEN = "DELIVERY.SEND.FORBIDDEN"
    DELIVERY_RECEIPT_FAILED = "DELIVERY.RECEIPT.FAILED"

    # AUTH
    AUTH_MFA_REPLAYED = "AUTH.MFA.REPLAYED"
    AUTH_MFA_LOCKED = "AUTH.MFA.LOCKED"
    AUTH_SESSION_EXPIRED = "AUTH.SESSION.EXPIRED"

    # BACKUP
    BACKUP_RESTORE_APPROVAL_INVALID = "BACKUP.RESTORE.APPROVAL_INVALID"
    BACKUP_RESTORE_CHECKSUM_MISMATCH = "BACKUP.RESTORE.CHECKSUM_MISMATCH"

    # EFFECT_RECEIPT
    EFFECT_RECEIPT_MANAGER_UNAVAILABLE = "EFFECT.RECEIPT.MANAGER_UNAVAILABLE"
    EFFECT_RECEIPT_DB_ERROR = "EFFECT.RECEIPT.DB_ERROR"
